using System;
using System.Collections.Generic;
using System.Globalization;
using System.Xml.Linq;
using TPLib.Localization;
using TheLastStand.Definition.Item;
using TheLastStand.Framework.Extensions;
using TheLastStand.Framework.Serialization;
using TheLastStand.View.Unit.Stat;
using UnityEngine;

namespace TheLastStand.Definition.Unit.Trait;

public class UnitTraitDefinition : TheLastStand.Framework.Serialization.Definition
{
	public static class Constants
	{
		public const string BadNbOutlined = "BadNbOutlined";

		public const string GoodNbOutlined = "GoodNbOutlined";

		public const string LocEffectDescEquipmentSlot = "UnitTrait_EffectDesc_EquipmentSlot";

		public const string OneArmedId = "One-Armed";
	}

	public class SlotModifier
	{
		private string descriptionOverrideKey = string.Empty;

		public bool AddSlot { get; private set; }

		public int Amount { get; private set; }

		public ItemSlotDefinition.E_ItemSlotId Name { get; private set; }

		public SlotModifier(ItemSlotDefinition.E_ItemSlotId name, int amount, bool addSlot, string descriptionOverrideKey)
		{
			AddSlot = addSlot;
			Amount = amount;
			Name = name;
			this.descriptionOverrideKey = descriptionOverrideKey;
		}

		public string GetDescription()
		{
			if (string.IsNullOrEmpty(descriptionOverrideKey))
			{
				if (Localizer.Exists("UnitTrait_EffectDesc_EquipmentSlot"))
				{
					return string.Format(Localizer.Get("UnitTrait_EffectDesc_EquipmentSlot"), string.Format("<style=\"{0}\">{1}{2}</style>", AddSlot ? "GoodNbOutlined" : "BadNbOutlined", AddSlot ? "+" : "-", Amount), Localizer.Get("CategoryName_" + Name));
				}
				Debug.LogWarning("UnitTraitDefinition.SlotModifier.GetDescription() ERROR: UnitTrait_EffectDesc_EquipmentSlot key not found in localization. Using description generated by default instead.");
				return "<style=\"" + (AddSlot ? "GoodNbOutlined" : "BadNbOutlined") + "\">" + (AddSlot ? "+" : "-") + string.Format("{0}</style> {1} slot{2}", Amount, Name, (Amount > 1) ? "s" : string.Empty);
			}
			if (Localizer.Exists(descriptionOverrideKey))
			{
				return Localizer.Get(descriptionOverrideKey);
			}
			Debug.LogWarning("UnitTraitDefinition.SlotModifier.GetDescription() ERROR: " + descriptionOverrideKey + " not found in localization. Using default description instead.");
			return "<style=\"" + (AddSlot ? "GoodNbOutlined" : "BadNbOutlined") + "\">" + (AddSlot ? "+" : "-") + string.Format("{0}</style> {1} slot{2}", Amount, Name, (Amount > 1) ? "s" : string.Empty);
		}
	}

	public class StatModifier
	{
		private string descriptionOverrideKey = string.Empty;

		public UnitStatDefinition.E_Stat Stat { get; private set; } = UnitStatDefinition.E_Stat.Undefined;

		public float Value { get; private set; }

		public StatModifier(UnitStatDefinition.E_Stat stat, float value, string descriptionOverrideKey)
		{
			Stat = stat;
			Value = value;
			this.descriptionOverrideKey = descriptionOverrideKey;
		}

		public string GetDescription(bool getStylizedStatNames = false)
		{
			if (string.IsNullOrEmpty(descriptionOverrideKey))
			{
				if (!getStylizedStatNames)
				{
					return Stat.GetValueStylized(Value) + " " + UnitStatDisplay.GetStatIconToString(Stat) + " " + Localizer.Get("UnitStat_Name_" + Stat);
				}
				return Stat.GetValueStylized(Value) + " " + Stat.GetStylizedName();
			}
			if (Localizer.Exists(descriptionOverrideKey))
			{
				return Localizer.Get(descriptionOverrideKey);
			}
			Debug.LogWarning("UnitTraitDefinition.StatModifier.GetDescription() ERROR: " + descriptionOverrideKey + " not found in localization. Using default description instead.");
			return Stat.GetValueStylized(Value) + " " + UnitStatDisplay.GetStatIconToString(Stat) + " " + Localizer.Get("UnitStat_Name_" + Stat);
		}
	}

	public int Cost { get; private set; }

	public int Duration { get; private set; }

	public string Id { get; private set; }

	public bool IsBackgroundTrait { get; private set; }

	public List<string> Incompatibilities { get; private set; } = new List<string>();

	public List<string> RaceIncompatibilities { get; private set; } = new List<string>();

	public List<StatModifier> StatModifiers { get; private set; } = new List<StatModifier>();

	public List<SlotModifier> AddSlots { get; private set; } = new List<SlotModifier>();

	public string Name => Localizer.Get("UnitTrait_Name_" + Id);

	public List<SlotModifier> RemoveSlots { get; private set; } = new List<SlotModifier>();

	public UnitTraitDefinition(XContainer container)
		: base(container)
	{
	}

	public override void Deserialize(XContainer container)
	{
		XElement xElement = container as XElement;
		XAttribute xAttribute = xElement.Attribute("Id");
		if (xAttribute.IsNullOrEmpty())
		{
			Debug.LogError("UnitTraitDefinition must have Id!");
			return;
		}
		Id = xAttribute.Value;
		XAttribute xAttribute2 = xElement.Attribute("IsBackgroundTrait");
		if (!xAttribute2.IsNullOrEmpty())
		{
			if (!bool.TryParse(xAttribute2.Value, out var result))
			{
				Debug.LogError("UnitTraitDefinition " + Id + " must have a valid IsBackgroundTrait (bool)");
				return;
			}
			IsBackgroundTrait = result;
		}
		XElement xElement2 = xElement.Element("Cost");
		if (xElement2 == null)
		{
			Debug.LogError("UnitTraitDefinition " + Id + " must have an element Cost");
			return;
		}
		XAttribute xAttribute3 = xElement2.Attribute("Value");
		if (xAttribute3.IsNullOrEmpty())
		{
			Debug.LogError("UnitTraitDefinition " + Id + " Cost must have an attribute Value");
			return;
		}
		if (!int.TryParse(xAttribute3.Value, NumberStyles.Integer, CultureInfo.InvariantCulture, out var result2))
		{
			Debug.LogError("UnitTraitDefinition " + Id + " Cost must have a valid attribute Value (int)");
			return;
		}
		Cost = result2;
		string empty = string.Empty;
		foreach (XElement item in xElement.Elements("StatModifier"))
		{
			XAttribute xAttribute4 = item.Attribute("Stat");
			if (xAttribute4 == null)
			{
				Debug.LogError("The StatModifier has no stat!");
				continue;
			}
			XAttribute xAttribute5 = item.Attribute("DescOverrideKey");
			empty = ((xAttribute5 != null) ? xAttribute5.Value : string.Empty);
			StatModifiers.Add(new StatModifier((UnitStatDefinition.E_Stat)Enum.Parse(typeof(UnitStatDefinition.E_Stat), xAttribute4.Value), float.Parse(item.Value, NumberStyles.Float, CultureInfo.InvariantCulture), empty));
		}
		ItemSlotDefinition.E_ItemSlotId e_ItemSlotId = ItemSlotDefinition.E_ItemSlotId.None;
		int num = 0;
		foreach (XElement item2 in xElement.Elements("AddSlot"))
		{
			XAttribute xAttribute6 = item2.Attribute("Slot");
			if (xAttribute6.IsNullOrEmpty())
			{
				Debug.LogError("The unitTraitDefinition AddSlot has no slot!");
				continue;
			}
			if (!Enum.TryParse<ItemSlotDefinition.E_ItemSlotId>(xAttribute6.Value, out var result3))
			{
				Debug.LogError("An unitTraitDefinition has an invalid SlotId " + xAttribute6.Value + "!");
			}
			e_ItemSlotId = result3;
			XAttribute xAttribute7 = item2.Attribute("Amount");
			num = ((xAttribute7 == null) ? 1 : int.Parse(xAttribute7.Value));
			XAttribute xAttribute8 = item2.Attribute("DescOverrideKey");
			empty = ((xAttribute8 != null) ? xAttribute8.Value : string.Empty);
			AddSlots.Add(new SlotModifier(e_ItemSlotId, num, addSlot: true, empty));
		}
		foreach (XElement item3 in xElement.Elements("RemoveSlot"))
		{
			XAttribute xAttribute9 = item3.Attribute("Slot");
			if (xAttribute9.IsNullOrEmpty())
			{
				Debug.LogError("The unitTraitDefinition RemoveSlots has no slot!");
				continue;
			}
			if (!Enum.TryParse<ItemSlotDefinition.E_ItemSlotId>(xAttribute9.Value, out var result4))
			{
				Debug.LogError("An unitTraitDefinition has an invalid SlotId " + xAttribute9.Value + "!");
			}
			e_ItemSlotId = result4;
			XAttribute xAttribute10 = item3.Attribute("Amount");
			num = ((xAttribute10 == null) ? 1 : int.Parse(xAttribute10.Value));
			XAttribute xAttribute11 = item3.Attribute("DescOverrideKey");
			empty = ((xAttribute11 != null) ? xAttribute11.Value : string.Empty);
			RemoveSlots.Add(new SlotModifier(e_ItemSlotId, num, addSlot: false, empty));
		}
		XElement xElement3 = xElement.Element("Duration");
		if (xElement3 != null)
		{
			Duration = int.Parse(xElement3.Value);
		}
		XElement xElement4 = xElement.Element("Incompatibilities");
		if (xElement4 == null)
		{
			return;
		}
		foreach (XElement item4 in xElement4.Elements("UnitTraitDefinition"))
		{
			XAttribute xAttribute12 = item4.Attribute("Id");
			if (xAttribute12 == null)
			{
				Debug.LogError("The unit trait incompatibility has no Id!");
			}
			else
			{
				Incompatibilities.Add(xAttribute12.Value);
			}
		}
		foreach (XElement item5 in xElement4.Elements("Race"))
		{
			XAttribute xAttribute13 = item5.Attribute("Id");
			if (xAttribute13 == null)
			{
				Debug.LogError("The unit race incompatibility has no Id!");
			}
			else
			{
				RaceIncompatibilities.Add(xAttribute13.Value);
			}
		}
	}

	public string GetDescription()
	{
		string text = string.Empty;
		for (int i = 0; i < AddSlots.Count; i++)
		{
			text = text + AddSlots[i].GetDescription() + "\n";
		}
		for (int j = 0; j < RemoveSlots.Count; j++)
		{
			text = text + RemoveSlots[j].GetDescription() + "\n";
		}
		for (int k = 0; k < StatModifiers.Count; k++)
		{
			text = text + StatModifiers[k].GetDescription() + "\n";
		}
		return text;
	}
}
